### ISSUE TITLE
Ouch! Careful with the auto-format!

### ISSUE THREAD

**Issue by DRNadler** [GitHubLionel/wxMathPlot#35]
I just tried to merge a bunch of documentation corrections and minor touchups.
The merge failed because the code I recently added (bounding box stuff) had been reformatted.
It looks like some auto-reformatting happened somewhere.
In addition to making the code much harder to read, now the merge fails......
Ouch!

**Comment by asmwarrior** [comment]
You mean some code are using "two spaces" as indent, but some code are using "one tab" as indent char? Maybe some are using "4 spaces" as intent char.

**Comment by DRNadler** [comment]
In [your latest commit](https://github.com/GitHubLionel/wxMathPlot/commit/dc6dd21cd8636b95aad9377a8446360b274c722e), the bounding box functions I added were reformatted into many more lines. This unfortunately made the git merge function fail when I try to commit my latest changes. I'm trying to stick with the original code style which seemed to use spaces not tabs and often indented in multiple of 2 spaces. Unfortunately source indenting is quite random now?

**Comment by GitHubLionel** [comment]
The format I use is :
- no tab because the indentation is not regular. So tab is replaced by spaces
- 2 spaces for indentation. So the code is more compact and lines not too long
- next several rules like brace at beginning of line, ...
I use Eclipse and maybe I can send my editor profile. But I don't think that you can use it.
In fact, when I get your code, it is reformated when I use it.

**Comment by DRNadler** [comment]
I had to delete my fork and create a new one to be able to merge...
